import = ["~/.config/alacritty/venus.toml"]

[font]
normal = { family = "IntoneMono Nerd Font", style = "Medium" }
bold = { family = "IntoneMono Nerd Font", style = "Bold" }
italic = { family = "IntoneMono Nerd Font", style = "Italic" }
bold_italic = { family = "IntoneMono Nerd Font", style = "Bold Italic" }
size = 14
glyph_offset = { x = 0, y = 0 }

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 0 }
opacity = 0.95
decorations = "None"
